name: Release

on:
   push:
      tags:
         - 'v*.*.*'

jobs:
   build:

      runs-on: ubuntu-latest

      steps:
         -  name: Checkout repository
            uses: actions/checkout@v2

         -  name: Setup .NET Core
            uses: actions/setup-dotnet@v1
            with:
               dotnet-version: 8.x.x

         -  name: Git version
            id: gitVersion
            shell: bash
            run: |
               FULL_VERSION=$(git describe --tags --dirty --long --abbrev=10)
               VERSION=$(echo $FULL_VERSION | sed 's/\(v\)\([0-9][0-9]*\).*\.\([0-9][0-9]*\).*\.\([0-9][0-9]*\).*/\2.\3.\4/')
               echo ::set-output name=gitfullversion::$FULL_VERSION
               echo ::set-output name=gitversion::$VERSION

         -  name: Build
            run: dotnet build --configuration Release -p:AssemblyVersion=${{ steps.gitVersion.outputs.gitversion }} -p:FileVersion=${{ steps.gitVersion.outputs.gitversion }} -p:InformationalVersion=${{ steps.gitVersion.outputs.gitfullversion }} -p:PackageVersion=${{ steps.gitVersion.outputs.gitversion }}

         -  name: Publish nuget
            run: dotnet nuget push "LicenseGenerator/bin/Release/*.nupkg" -k ${{secrets.NugetOrgToken}} -s https://api.nuget.org/v3/index.json
